name: Frontend Deployment

on:
    push:
        branches: [ main ]
        paths:
          - 'frontend/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Az CLI login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Run Azure CLI commands
      #   run: |
      #     az account show
      #     az group list
      #     pwd 

      - name: Upload to blob storage
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name azresumestorageacc --destination-container '$web' --source frontend/ --overwrite

      - name: Purge CDN endpoint
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az cdn endpoint purge --content-paths  "/*" --profile-name "azrescdn" --name "azrescdn" --resource-group "azure-resume"

    # Azure logout
      - name: logout
        run: |
          az logout
        if: always()